// Code generated by ent, DO NOT EDIT.

package datasharesession

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the datasharesession type in the database.
	Label = "data_share_session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTrajectoryID holds the string denoting the trajectory_id field in the database.
	FieldTrajectoryID = "trajectory_id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldDataset holds the string denoting the dataset field in the database.
	FieldDataset = "dataset"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldRequestPath holds the string denoting the request_path field in the database.
	FieldRequestPath = "request_path"
	// FieldUserAgent holds the string denoting the user_agent field in the database.
	FieldUserAgent = "user_agent"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldIsFinalSnapshot holds the string denoting the is_final_snapshot field in the database.
	FieldIsFinalSnapshot = "is_final_snapshot"
	// FieldSourceRequestCount holds the string denoting the source_request_count field in the database.
	FieldSourceRequestCount = "source_request_count"
	// FieldSystemPrompt holds the string denoting the system_prompt field in the database.
	FieldSystemPrompt = "system_prompt"
	// FieldTools holds the string denoting the tools field in the database.
	FieldTools = "tools"
	// FieldMessages holds the string denoting the messages field in the database.
	FieldMessages = "messages"
	// FieldUsage holds the string denoting the usage field in the database.
	FieldUsage = "usage"
	// FieldMeta holds the string denoting the meta field in the database.
	FieldMeta = "meta"
	// FieldSessionJSON holds the string denoting the session_json field in the database.
	FieldSessionJSON = "session_json"
	// FieldPayloadCompressed holds the string denoting the payload_compressed field in the database.
	FieldPayloadCompressed = "payload_compressed"
	// FieldPayloadEncoding holds the string denoting the payload_encoding field in the database.
	FieldPayloadEncoding = "payload_encoding"
	// FieldPayloadBytes holds the string denoting the payload_bytes field in the database.
	FieldPayloadBytes = "payload_bytes"
	// FieldExportable holds the string denoting the exportable field in the database.
	FieldExportable = "exportable"
	// FieldQualityStatus holds the string denoting the quality_status field in the database.
	FieldQualityStatus = "quality_status"
	// FieldQualityErrors holds the string denoting the quality_errors field in the database.
	FieldQualityErrors = "quality_errors"
	// FieldStorageBytes holds the string denoting the storage_bytes field in the database.
	FieldStorageBytes = "storage_bytes"
	// FieldInputTokens holds the string denoting the input_tokens field in the database.
	FieldInputTokens = "input_tokens"
	// FieldOutputTokens holds the string denoting the output_tokens field in the database.
	FieldOutputTokens = "output_tokens"
	// FieldTotalTokens holds the string denoting the total_tokens field in the database.
	FieldTotalTokens = "total_tokens"
	// FieldActualCost holds the string denoting the actual_cost field in the database.
	FieldActualCost = "actual_cost"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldEndedAt holds the string denoting the ended_at field in the database.
	FieldEndedAt = "ended_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the datasharesession in the database.
	Table = "data_share_sessions"
)

// Columns holds all SQL columns for datasharesession fields.
var Columns = []string{
	FieldID,
	FieldTrajectoryID,
	FieldSessionID,
	FieldDataset,
	FieldProvider,
	FieldModel,
	FieldRequestPath,
	FieldUserAgent,
	FieldStatus,
	FieldIsFinalSnapshot,
	FieldSourceRequestCount,
	FieldSystemPrompt,
	FieldTools,
	FieldMessages,
	FieldUsage,
	FieldMeta,
	FieldSessionJSON,
	FieldPayloadCompressed,
	FieldPayloadEncoding,
	FieldPayloadBytes,
	FieldExportable,
	FieldQualityStatus,
	FieldQualityErrors,
	FieldStorageBytes,
	FieldInputTokens,
	FieldOutputTokens,
	FieldTotalTokens,
	FieldActualCost,
	FieldUserID,
	FieldAPIKeyID,
	FieldGroupID,
	FieldCreatedAt,
	FieldEndedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TrajectoryIDValidator is a validator for the "trajectory_id" field. It is called by the builders before save.
	TrajectoryIDValidator func(string) error
	// SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	SessionIDValidator func(string) error
	// DatasetValidator is a validator for the "dataset" field. It is called by the builders before save.
	DatasetValidator func(string) error
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// DefaultRequestPath holds the default value on creation for the "request_path" field.
	DefaultRequestPath string
	// RequestPathValidator is a validator for the "request_path" field. It is called by the builders before save.
	RequestPathValidator func(string) error
	// DefaultUserAgent holds the default value on creation for the "user_agent" field.
	DefaultUserAgent string
	// UserAgentValidator is a validator for the "user_agent" field. It is called by the builders before save.
	UserAgentValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultIsFinalSnapshot holds the default value on creation for the "is_final_snapshot" field.
	DefaultIsFinalSnapshot bool
	// DefaultSourceRequestCount holds the default value on creation for the "source_request_count" field.
	DefaultSourceRequestCount int
	// DefaultPayloadEncoding holds the default value on creation for the "payload_encoding" field.
	DefaultPayloadEncoding string
	// PayloadEncodingValidator is a validator for the "payload_encoding" field. It is called by the builders before save.
	PayloadEncodingValidator func(string) error
	// DefaultPayloadBytes holds the default value on creation for the "payload_bytes" field.
	DefaultPayloadBytes int64
	// DefaultExportable holds the default value on creation for the "exportable" field.
	DefaultExportable bool
	// DefaultQualityStatus holds the default value on creation for the "quality_status" field.
	DefaultQualityStatus string
	// QualityStatusValidator is a validator for the "quality_status" field. It is called by the builders before save.
	QualityStatusValidator func(string) error
	// DefaultStorageBytes holds the default value on creation for the "storage_bytes" field.
	DefaultStorageBytes int64
	// DefaultInputTokens holds the default value on creation for the "input_tokens" field.
	DefaultInputTokens int64
	// DefaultOutputTokens holds the default value on creation for the "output_tokens" field.
	DefaultOutputTokens int64
	// DefaultTotalTokens holds the default value on creation for the "total_tokens" field.
	DefaultTotalTokens int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the DataShareSession queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTrajectoryID orders the results by the trajectory_id field.
func ByTrajectoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrajectoryID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByDataset orders the results by the dataset field.
func ByDataset(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDataset, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByRequestPath orders the results by the request_path field.
func ByRequestPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestPath, opts...).ToFunc()
}

// ByUserAgent orders the results by the user_agent field.
func ByUserAgent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserAgent, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByIsFinalSnapshot orders the results by the is_final_snapshot field.
func ByIsFinalSnapshot(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsFinalSnapshot, opts...).ToFunc()
}

// BySourceRequestCount orders the results by the source_request_count field.
func BySourceRequestCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceRequestCount, opts...).ToFunc()
}

// BySystemPrompt orders the results by the system_prompt field.
func BySystemPrompt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSystemPrompt, opts...).ToFunc()
}

// ByPayloadEncoding orders the results by the payload_encoding field.
func ByPayloadEncoding(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayloadEncoding, opts...).ToFunc()
}

// ByPayloadBytes orders the results by the payload_bytes field.
func ByPayloadBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayloadBytes, opts...).ToFunc()
}

// ByExportable orders the results by the exportable field.
func ByExportable(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExportable, opts...).ToFunc()
}

// ByQualityStatus orders the results by the quality_status field.
func ByQualityStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQualityStatus, opts...).ToFunc()
}

// ByStorageBytes orders the results by the storage_bytes field.
func ByStorageBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStorageBytes, opts...).ToFunc()
}

// ByInputTokens orders the results by the input_tokens field.
func ByInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokens, opts...).ToFunc()
}

// ByOutputTokens orders the results by the output_tokens field.
func ByOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTokens, opts...).ToFunc()
}

// ByTotalTokens orders the results by the total_tokens field.
func ByTotalTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalTokens, opts...).ToFunc()
}

// ByActualCost orders the results by the actual_cost field.
func ByActualCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualCost, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByEndedAt orders the results by the ended_at field.
func ByEndedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
